const CREATED = 201;
const SUCCESS = 200;
const INVALID_DATA = 400;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;

module.exports = {
  CREATED,
  SUCCESS,
  INVALID_DATA,
  NOT_FOUND,
  DEFAULT_ERROR,
};
